### ISSUE TITLE
As a customer, I want to see all available products so that I can choose what to buy

### ISSUE THREAD

**Issue by EeroVallistu** [EeroVallistu/dropshipwebpage#5]
- [ ] A product list is displayed on the home page.

**Comment by EeroVallistu** [comment]
![checkout](https://github.com/user-attachments/assets/4560a9f5-310e-4f99-9283-2bcc938662c9)
Checkout page

**Comment by henno** [comment]
"Products can be filtered by category." peaks olema eraldi lugu, sest ilma selleta saab väga vabalt seda lugu teha.
