### ISSUE TITLE
As an administrator, I want to log in to the admin page with password

### ISSUE THREAD

**Issue by EeroVallistu** [EeroVallistu/dropshipwebpage#8]
- [ ] I can access the admin login page.
- [ ] I can enter my username and password.
- [ ] I can see an error message if the login credentials are incorrect.
- [ ] I can be redirected to the admin dashboard upon successful login.
- [ ] I can log out from the admin dashboard.

**Comment by EeroVallistu** [comment]
![main page](https://github.com/user-attachments/assets/73ea3b14-e4af-4a93-a858-2d1a1540f704)
Cart number that show how many products are in it

**Comment by henno** [comment]
Siin on jälle mitu lugu koos. Löö lahku.

**Comment by henno** [comment]
> Siin on jälle mitu lugu koos. Löö lahku.

I can sign in and out
I can view products 
I can add products
I can edit products
I can delete products
